import { readFile } from "node:fs/promises";
import path from "node:path";

import {
  entryAnchor,
  entryBody,
  entrySlug,
  groupAnchor,
  parseExport,
  type NixdocEntry,
  type NixdocGroup,
} from "./nixdoc";
import {
  containers,
  headings,
  inlineAnchorIds,
  leadText,
  shiftHeadings,
  toCommonmark,
  type AnchorTarget,
} from "./nixpkgs-markdown";

export const docRoot = path.resolve(
  process.env.NIXPKGS_DOC_DIR ?? "./nixpkgs-doc",
);

export interface NavLeaf {
  file: string;
  label?: string;
  "id-prefix"?: string;
}

export interface NavGroup {
  label: string;
  id: string;
  children: NavNode[];
}

export interface NavCollection {
  collection: string;
  type: "nixdoc";
}

export type NavNode = NavLeaf | NavGroup | NavCollection;

export interface Nav {
  items: NavNode[];
  open: string[];
}

export async function readNav(): Promise<Nav> {
  const file = path.join(docRoot, "nav.json");
  const nav = JSON.parse(await readFile(file, "utf8"));
  if (!Array.isArray(nav?.items)) {
    throw new Error(`${file}: missing 'items'`);
  }
  const groups = (nodes: NavNode[]): void => {
    for (const node of nodes) {
      if (!("children" in node)) continue;
      if (!node.id) throw new Error(`${file}: group '${node.label}' has no id`);
      groups(node.children);
    }
  };
  groups(nav.items);
  return { items: nav.items, open: nav.open ?? [] };
}

export async function readRevision(): Promise<string> {
  try {
    return (await readFile(path.join(docRoot, ".revision"), "utf8")).trim();
  } catch {
    return "master";
  }
}

/** A manual page from one markdown file of the nixpkgs doc tree. */
export interface DocPage {
  /** Resource path below `/nixpkgs`, from the nav position of the file. */
  slug: string;
  href: string;
  title: string;
  file: string;
  /** CommonMark text, without the title heading the page renders separately. */
  body: string;
}

/** A page for one function of a nixdoc collection. */
export interface FunctionPage {
  /** Resource path below `/nixpkgs`: nav position, then the attribute path. */
  slug: string;
  href: string;
  attrPath: string;
  name: string;
  groups: string[];
  summary: string;
  source: NixdocEntry["source"];
  body: string;
}

/** A page for one function group of a nixdoc collection. */
export interface GroupPage {
  /** Resource path below `/nixpkgs`: nav position, then `lib/<group>`. */
  slug: string;
  href: string;
  id: string;
  summary: string;
  body: string;
}

/** A sidebar entry: either a link to a page or a labelled group of entries. */
export type TreeNode =
  { label: string; children: TreeNode[] } | { href: string; title: string };

export interface DocIndex {
  pages: DocPage[];
  functions: FunctionPage[];
  groups: GroupPage[];
  tree: TreeNode[];
}

/** Every nixpkgs resource path sits below this prefix. */
const BASE = "/nixpkgs";

/** A nixdoc collection documents the nixpkgs library, `lib`. */
const LIB_ROOT = "lib";

const SUFFIXES = [".chapter.md", ".section.md", ".part.md", ".md"];

/**
 * The nav id of a markdown file, one segment of its resource path.
 *
 * FIXME: nav.json gives every group a stable id. We forgot to add the same for files, this needs to be fixed upstream.
 *
 * If nixpkgs renames the file it moves the page-id.
 */
function leafId(file: string): string {
  const name = file.split("/").pop() ?? file;
  for (const suffix of SUFFIXES) {
    if (name.endsWith(suffix)) return name.slice(0, -suffix.length);
  }
  return name;
}

/** A markdown file with its title heading as seperate field. */
interface RawPage {
  slug: string;
  href: string;
  file: string;
  title: string;
  anchor?: string;
  markdown: string;
}

async function readPage(
  file: string,
  slug: string,
): Promise<RawPage | undefined> {
  let markdown: string;
  try {
    markdown = await readFile(path.join(docRoot, file), "utf8");
  } catch {
    console.warn(
      `nixpkgs doc: skipping ${file}, not in the doc root (generated by the nixpkgs manual build?)`,
    );
    return undefined;
  }
  const href = `${BASE}/${slug}`;
  const title = headings(markdown).find((heading) => heading.depth === 1);
  if (!title) {
    return {
      slug,
      href,
      file,
      title: slug.split("/").pop() ?? slug,
      markdown,
    };
  }
  const lines = markdown.split("\n");
  const at = lines.findIndex((line) => /^# /.test(line));
  lines.splice(at, 1);
  return {
    slug,
    href,
    file,
    // The h1 title may only have code tics, otherwise the syntax would leak.
    // FIXME: Enforce this rule in nixpkgs
    title: title.title.replace(/`/g, ""),
    ...(title.id ? { anchor: title.id } : {}),
    markdown: lines.join("\n").trimStart(),
  };
}

/** A nixdoc group plus the resource path of its page. */
type CollectedGroup = NixdocGroup & { slug: string };

/** A nixdoc entry plus the resource path of its page. */
type CollectedEntry = NixdocEntry & { slug: string };

async function readCollections(
  nodes: NavNode[],
  prefix: string[],
): Promise<{ groups: CollectedGroup[]; entries: CollectedEntry[] }> {
  const groups: CollectedGroup[] = [];
  const entries: CollectedEntry[] = [];
  const walk = async (items: NavNode[], at: string[]): Promise<void> => {
    for (const node of items) {
      if ("children" in node) {
        await walk(node.children, [...at, node.id]);
      } else if ("collection" in node && node.type === "nixdoc") {
        const file = path.join(docRoot, node.collection);
        const data = parseExport(
          file,
          JSON.parse(await readFile(file, "utf8")),
        );
        for (const group of data.groups) {
          groups.push({
            ...group,
            slug: [...at, LIB_ROOT, group.id].join("/"),
          });
        }
        for (const entry of data.entries) {
          entries.push({
            ...entry,
            slug: [...at, entrySlug(entry.id)].join("/"),
          });
        }
      }
    }
  };
  await walk(nodes, prefix);
  return { groups, entries };
}

let index: Promise<DocIndex> | undefined;

/**
 * FIXME: Delete this function after the manuals don't exist anymore.
 *
 * Bare ids like [](#sec-functions-library) need to be rewritten.
 * Example:
 *
 * [](#sec-functions-library) -> [heading text](/nixpkgs/<page>#sec-functions-library)
 *
 * How we do it:
 *
 * - Anchors are collected from every page before the body is converted.
 *
 *  1. Read nav.json, it maps the URL of each file.
 *  2. Read every markdown file and the anchors
 *  3. Build an anchor index and rewrite it
 */
export function loadDocIndex(): Promise<DocIndex> {
  index ??= buildDocIndex();
  return index;
}

async function buildDocIndex(): Promise<DocIndex> {
  const nav = await readNav();
  const revision = await readRevision();
  // reads manpage-urls.json once and cache it into the shared context
  // So the renderer pass can resolve '{manpage}nix.conf(5)'
  const manpageUrls: Record<string, string> = JSON.parse(
    await readFile(path.join(docRoot, "manpage-urls.json"), "utf8"),
  );

  const raw = new Map<string, RawPage>();
  const collectPages = async (
    nodes: NavNode[],
    prefix: string[],
  ): Promise<void> => {
    for (const node of nodes) {
      if ("children" in node) {
        await collectPages(node.children, [...prefix, node.id]);
      } else if ("file" in node) {
        const page = await readPage(
          node.file,
          [...prefix, leafId(node.file)].join("/"),
        );
        if (page) raw.set(node.file, page);
      }
    }
  };
  await collectPages(nav.items, []);

  const { groups, entries } = await readCollections(nav.items, []);

  const anchors = new Map<string, AnchorTarget>();
  const register = (markdown: string, href: string, fallback: string) => {
    for (const heading of headings(markdown)) {
      if (heading.id) {
        anchors.set(heading.id, {
          href: `${href}#${heading.id}`,
          text: heading.title,
        });
      }
    }
    for (const container of containers(markdown)) {
      anchors.set(container.id, {
        href: `${href}#${container.id}`,
        text: container.title,
      });
    }
    for (const id of inlineAnchorIds(markdown)) {
      anchors.set(id, { href: `${href}#${id}`, text: fallback });
    }
  };

  for (const page of raw.values()) {
    if (page.anchor) {
      anchors.set(page.anchor, { href: page.href, text: page.title });
    }
    register(page.markdown, page.href, page.title);
  }
  for (const group of groups) {
    const href = `${BASE}/${group.slug}`;
    anchors.set(groupAnchor(group.id), { href, text: group.id });
    register(group.description, href, group.id);
  }
  for (const entry of entries) {
    const href = `${BASE}/${entry.slug}`;
    anchors.set(entryAnchor(entry.id), { href, text: entry.attrPath });
    register(entry.description, href, entry.attrPath);
  }

  const convert = {
    manpageUrls,
    anchor: (id: string) => anchors.get(id),
    onDrop: (what: string) => console.warn(`nixpkgs doc: dropped ${what}`),
  };

  const pages = [...raw.values()].map((page) => ({
    slug: page.slug,
    href: page.href,
    title: page.title,
    file: page.file,
    body: toCommonmark(page.markdown, {
      ...convert,
      onDrop: (what) =>
        console.warn(`nixpkgs doc: ${page.file}: dropped ${what}`),
    }),
  }));

  const functions = entries.map((entry) => ({
    slug: entry.slug,
    href: `${BASE}/${entry.slug}`,
    attrPath: entry.attrPath,
    name: entry.name,
    groups: entry.groups,
    summary: leadText(entry.description),
    source: entry.source,
    body: entryBody(entry, revision, {
      ...convert,
      onDrop: (what) =>
        console.warn(`nixpkgs doc: ${entry.id}: dropped ${what}`),
    }),
  }));

  const tree = (nodes: NavNode[]): TreeNode[] =>
    nodes.flatMap((node): TreeNode[] => {
      if ("children" in node) {
        return [{ label: node.label, children: tree(node.children) }];
      }
      if ("collection" in node) {
        return [
          {
            label: LIB_ROOT,
            children: groups.map((group) => ({
              href: `${BASE}/${group.slug}`,
              title: group.id,
            })),
          },
        ];
      }
      const page = raw.get(node.file);
      if (!page) return [];
      return [{ href: page.href, title: node.label ?? page.title }];
    });

  return {
    pages,
    functions,
    groups: groups.map((group) => ({
      slug: group.slug,
      href: `${BASE}/${group.slug}`,
      id: group.id,
      summary: leadText(group.description),
      body: shiftHeadings(
        toCommonmark(group.description, {
          ...convert,
          onDrop: (what) =>
            console.warn(`nixpkgs doc: group ${group.id}: dropped ${what}`),
        }),
        1,
      ),
    })),
    tree: tree(nav.items),
  };
}
