[[redirects]]
from = "/manual/nix/unstable/*"
to = "https://hydra.nixos.org/job/nix/master/manual/latest/download/1/manual/:splat"
status = 200
force = true
[redirects.headers]
X-From = "nix.dev-Uogho3gi"

[[redirects]]
from = "/manual/nix/development/*"
to = "https://hydra.nixos.org/job/nix/master/manual/latest/download/1/manual/:splat"
status = 200
force = true
[redirects.headers]
X-From = "nix.dev-Uogho3gi"
