name: "Check site formatting"

on:
  push:
    branches:
      - master
  merge_group:
  pull_request:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          cache: npm
          cache-dependency-path: site/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - if: ${{ failure() }}
        run: |
          echo "::error :: Hey! It looks like the site is not formatted. Run 'npm run format' in site/ to fix it."
